currency_app:
  url: "http://api.exchangeratesapi.io/v1/"
  access_key: "381114cf116cbcfc4f05e4eb44625659"
  symbols:
    - 'GBP'
    - 'RUB'
    - 'UAH'
    - 'USD'
    - 'PLN'
  directory: "./app_currency_data/"

rd_api:
  url: "https://robot-dreams-de-api.herokuapp.com"
  endpoint: "/out_of_stock"
  username: "rd_dreams"
  password: "djT6LasE"
  directory: "./app_hw1_data/"